repos:
- repo: https://github.com/antonbabenko/pre-commit-terraform  #Follow the instructions as on the page to install dependencies
  rev: v1.64.0
  hooks:
  - id: terraform_fmt
  - id: terraform_docs
  - id: terraform_tflint
  - id: terragrunt_validate
  - id: terraform_tfsec
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.1.0
  hooks:
  - id: check-merge-conflict
  - id: detect-private-key
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.3.0
  hooks:
  - id: pretty-format-yaml
    args: [--autofix, --indent, '2']
